level_1_goals:
  - frage: "Warum ist dieses Ziel wichtig?"
  - frage: "Welche Nutzergruppen oder Rollen sind betroffen?"
  - frage: "Welche konkreten Ergebnisse sollen erreicht werden?"
  - frage: "Bis wann soll das Ziel erreicht sein?"
  - frage: "Welche Ressourcen sind erforderlich?"
  - frage: "Gibt es ein Budget oder finanzielle Einschränkungen?"
  - frage: "Welche Risiken bestehen bei der Zielverfolgung?"