- match: "Risiko"
  action: "Erstelle einen Risk Log und definiere Gegenmaßnahmen."
- match: "Stakeholder"
  action: "Führe eine Stakeholder-Analyse durch und erstelle einen Kommunikationsplan."
- match: "Tools"
  action: "Prüfe Tool-Bedarf und starte Beschaffungsprozess."
- match: "Zeitplan"
  action: "Erstelle mit dem Team einen Phasen/ Meilensteinplan."
- match: "Tenant Configuration"
  action: "Empfehlung: Priorisiere Azure AD Connect, um Identitätssynchronisation sicherzustellen und Berechtigungen zu prüfen."
- match: "Data Migration"
  action: "Empfehlung: Führe einen Migrationstest in einer isolierten Staging-Umgebung durch und prüfe die Datenintegrität."
- match: "Security & Compliance"
  action: "Empfehlung: Definiere DLP-Richtlinien und Conditional Access-Prozesse, um Datenschutz und Zugriffssteuerung zu gewährleisten."
- match: "User Adoption"
  action: "Empfehlung: Organisiere Workshops und Schulungen für Pilotanwender, um Feedback frühzeitig zu integrieren."
- match: "Change Management"
  action: "Empfehlung: Erstelle einen Kommunikationsplan für Stakeholder und plane regelmäßige Statusupdates."
- match: "Reporting"
  action: "Empfehlung: Automatisiere wöchentliche Reports mit KPIs zu Nutzung und Fortschritt."
  